

FROM python:3.13-slim

RUN apt-get update && \
    apt-get install -y curl gnupg git && \
    rm -rf /var/lib/apt/lists/* 


RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get update && \
    apt-get install -y nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/apt/lists/* 


RUN node -v && npm -v


WORKDIR /app


RUN git clone https://github.com/creepereye1204/fastapi-react.git .


CMD ["tail", "-f", "/dev/null"]


